# Generated by Django 2.2.3 on 2019-08-02 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['date_time']},
        ),
    ]
