# Generated by Django 2.2.3 on 2019-08-05 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information_sheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information',
            options={'ordering': ['date_time']},
        ),
    ]
